### PR TITLE
Update .styleci.yml

### PR DESCRIPTION
**Pull request by justinparis**
### Checklist

- [ ] I've followed the _DocsPen_ code style and run **StyleCI** to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/DocsPen/Platform/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by yoginth** [comment]
yeah awesome

**Comment by justinparis** [comment]
still the @docspen-bot is not waked up!

**Comment by yoginth** [comment]
working on it!

**Comment by yoginth** [comment]
@docspen-bot 1

**Comment by yoginth** [comment]
@docspen-bot 2

**Comment by yoginth** [comment]
@docspen-bot 2

**Comment by yoginth** [comment]
@docspen-bot 3

**Comment by yoginth** [comment]
@docspen-bot 4

**Pull request closed without merging**
